### ISSUE TITLE
QA Checklist

### ISSUE THREAD

**Issue by TwixmixyJanet** [abenedetti27/recipe-rolodex#105]
Overall:

- [x] - Need to update the entire site to look great thematically
- [x] - If authorization is working then we need to update forced auth pages to be based off the person logged in. (we may want to do this step later as we continue working on look and feel of everything)
- [x] - Every page needs to be looked at with a mobile view in mind, lots of room for improvement here

Home page aka '/':

- [x] - Navbar needs to have logo
- [x] - Navbar needs to have home, login (when not logged in)
- [x] - Navbar needs to have home, dashboard, pinned posts, logout (when logged in)
- [x] - Navbar Search needs to be cleaned up and become functional
- [x] - Footer needs to be updated to be relevant data
- [x] - Footer needs to stick to the bottom no matter the size of the page
- [x] - Carousel image(s) need updated)

Recipe page aka '/recipe:id':

- [x] - Needs to visually look better (may be a change when we apply overall thematic look)
- [x] - Family badge needs to link to whichever family is related to recipe
- [x] - Pin/unpin functionality is needed

Dashboard page aka '/dashboard':

- [x] - Modal functionality needs finalized to be able to create and add a family
- [x] - Add new recipe needs to be linked up
- [x] - Visually needs to look better (again may be overall thematic css)
- [x] Need to have the delete and edit buttons for each recipe
- [x] Delete functionality needs to refresh state once deleted
- [x] Edit functionality needs to populate existing data to recipe form

AddRecipe(RecipeForm) aka '/addrecipe':

- [x] - None of the form submission fields are functional yet
- [x] - Cloudinary appears to be uploading to the cloud, but need to connect it to our field submission data as well
- [x] - Need the family drop down field to populate with the families related to the user logged in
- [x] Once done here copy this code to create the edit recipe component
- [x] Photo preview stopped displaying, need to investigate

RecipeSearch(???) aka '/???':
- [x] - We don't have a page created for when someone does a search on recipes. Is this a functionality we want/need?? probably.
- [x] Connect recipe search to navbar search field
- [x] - Currently we have a route for '/familysearch' on main - do we need this anymore since we're doing this through the modal?

Login:

- [x] Update so user is rerouted to their dashboard after logging in or signing up
